class ChatModel {
  final String name;
  final String message;
  final String time;
  final String avatarUrl;
  final bool seen, online, me;

  ChatModel({
    required this.name,
    required this.message,
    required this.time,
    required this.avatarUrl,
    required this.seen,
    required this.online,
    this.me = false,
  });
}

List<ChatModel> dummyData = [
  ChatModel(
      name: "Shekina David",
      message: "Salut, y'a encore quelques soucis a l'UPN !",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/17.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Bibine Mutax",
      message: "On se voit heure ?, je me prepare",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/35.jpg",
      seen: false,
      online: true,
      me: true),
  ChatModel(
      name: "My Only Girl",
      message: "Encore yo 😂, tu ne vas pas changer",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/24.jpg",
      seen: false,
      online: true,
      me: true),
  ChatModel(
      name: "Damso",
      message: "D'accord brow",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/88.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Gabriella Mateta",
      message: "Merci beaucoup, j'espere te revoir bientot !",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/85.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Sarah Mimosas",
      message: "Oui, le courant est retabli",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/50.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Patrick Tieks",
      message: "Je pense pas...",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/61.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Mme Rose",
      message: "Salut mon grand",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/13.jpg",
      seen: true,
      online: true,
      me: false),
  ChatModel(
      name: "Modart Kilelo",
      message: "Je t'ecrirais une fois toutes les articles p...",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/38.jpg",
      seen: true,
      online: false,
      me: true),
  ChatModel(
      name: "Oncle John",
      message: "Pour les bons d'achats, il ne font pas des re...",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/50.jpg",
      seen: true,
      online: true,
      me: true),
  ChatModel(
      name: "My Only Girl",
      message: "Encore yo 😂, tu ne vas pas changer",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/24.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Damso",
      message: "D'accord brow",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/88.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Gabriella Mateta",
      message: "Merci beaucoup, j'espere te revoir bientot !",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/85.jpg",
      seen: true,
      online: true,
      me: false),
  ChatModel(
      name: "Sarah Mimosas",
      message: "Oui, le courant est retabli",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/50.jpg",
      seen: true,
      online: true,
      me: false),
  ChatModel(
      name: "Patrick Tieks",
      message: "Je pense pas...",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/61.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Mme Rose",
      message: "Salut mon grand",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/13.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Shekina David",
      message: "Salut, y'a encore quelques soucis a l'UPN !",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/17.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Sabine Mutax",
      message: "On se voit a quelle heure ?, je me prepare",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/35.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "My Only Girl",
      message: "Encore yo 😂, tu ne vas pas changer",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/24.jpg",
      seen: false,
      online: true,
      me: false),
  ChatModel(
      name: "Damso",
      message: "D'accord brow",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/88.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Gabriella Mateta",
      message: "Merci beaucoup, j'espere te revoir bientot !",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/85.jpg",
      seen: true,
      online: true,
      me: false),
  ChatModel(
      name: "Sarah Mimosas",
      message: "Oui, le courant est retabli",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/50.jpg",
      seen: true,
      online: true,
      me: false),
  ChatModel(
      name: "Patrick Tieks",
      message: "Je pense pas...",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/men/61.jpg",
      seen: true,
      online: false),
  ChatModel(
      name: "Mme Rose",
      message: "Salut mon grand",
      time: "15:34",
      avatarUrl: "https://randomuser.me/portraits/women/13.jpg",
      seen: false,
      online: true,
      me: false),
];
